language: ruby


rvm:
  - "1.9.3"
  
env:
  - COVERAGE_REPORTS=shippable/codecoverage
  
archive: true
notifications:
  email:
     recipients:
        - vidya@shippable.com
        - buildsampletest@gmail.com
     on_success: always
     on_failure: always

    
