language: ruby


rvm:
  - "1.9.3"
  - "1.9.2
  
env:
  - COVERAGE_REPORTS=shippable/codecoverage
  
archive: true
after_script:
  - cp README.md ./shippable/codecoverage
notifications:
  email:
     recipients:
        - vidya@shippable.com
        - buildsampletest@gmail.com
     on_success: always
     on_failure: always

    
